package cn.utstarcom.vmsadapter.md5verify.pojo;
// Generated 2017-11-20 17:00:17 by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MediaContent generated by hbm2java
 */
@Entity
@Table(name = "MEDIACONTENT", schema = "WACOS")
public class MediaContent implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private int mediaContentId;
    private String contentName;
    private String code;
    private String code2;
    private Character type;
    private Character closedCaption;
    private Character status;
    private Character screenFormat;
    private Boolean audioType;
    private String fileUrl;
    private Integer contentDefid;
    private Integer vspId;
    private Date createDate;
    private Integer createStaffid;
    private Date lastUpdateTime;
    private String cdnDomainCode;
    private String originalFileUrl;
    private Character internalFlag;
    private Character priority;
    private Character transcodeFlag;
    private Integer tcsOriginalContentDefid;
    private Integer tcsTargetContentDefid;
    private String tcsOriginalFileUrl;
    private Character tcsStatus;
    private Character auditFlag;
    private String auditErrorCode;
    private String auditErrorInfo;
    private String auditResult;
    private String cdnDistributeLevel;
    private String parserErrorCode;
    private String parserErrorInfo;
    private String duration;
    private BigDecimal fileSize;
    private String verifyCode;
    private String tempFileName;
    private Integer nasServerId;

    public MediaContent() {
    }

    public MediaContent(int mediaContentId) {
        this.mediaContentId = mediaContentId;
    }

    public MediaContent(int mediaContentId, String contentName, String code, String code2,
            Character type, Character closedCaption, Character status, Character screenFormat,
            Boolean audioType, String fileUrl, Integer contentDefid, Integer vspId, Date createDate,
            Integer createStaffid, Date lastUpdateTime, String cdnDomainCode,
            String originalFileUrl, Character internalFlag, Character priority,
            Character transcodeFlag, Integer tcsOriginalContentDefid, Integer tcsTargetContentDefid,
            String tcsOriginalFileUrl, Character tcsStatus, Character auditFlag,
            String auditErrorCode, String auditErrorInfo, String auditResult,
            String cdnDistributeLevel, String parserErrorCode, String parserErrorInfo,
            String duration, BigDecimal fileSize, String verifyCode, String tempFileName,
            Integer nasServerId) {
        this.mediaContentId = mediaContentId;
        this.contentName = contentName;
        this.code = code;
        this.code2 = code2;
        this.type = type;
        this.closedCaption = closedCaption;
        this.status = status;
        this.screenFormat = screenFormat;
        this.audioType = audioType;
        this.fileUrl = fileUrl;
        this.contentDefid = contentDefid;
        this.vspId = vspId;
        this.createDate = createDate;
        this.createStaffid = createStaffid;
        this.lastUpdateTime = lastUpdateTime;
        this.cdnDomainCode = cdnDomainCode;
        this.originalFileUrl = originalFileUrl;
        this.internalFlag = internalFlag;
        this.priority = priority;
        this.transcodeFlag = transcodeFlag;
        this.tcsOriginalContentDefid = tcsOriginalContentDefid;
        this.tcsTargetContentDefid = tcsTargetContentDefid;
        this.tcsOriginalFileUrl = tcsOriginalFileUrl;
        this.tcsStatus = tcsStatus;
        this.auditFlag = auditFlag;
        this.auditErrorCode = auditErrorCode;
        this.auditErrorInfo = auditErrorInfo;
        this.auditResult = auditResult;
        this.cdnDistributeLevel = cdnDistributeLevel;
        this.parserErrorCode = parserErrorCode;
        this.parserErrorInfo = parserErrorInfo;
        this.duration = duration;
        this.fileSize = fileSize;
        this.verifyCode = verifyCode;
        this.tempFileName = tempFileName;
        this.nasServerId = nasServerId;
    }

    @Id

    @Column(name = "MEDIACONTENTID", unique = true, nullable = false, precision = 9, scale = 0)
    public int getMediaContentid() {
        return this.mediaContentId;
    }

    public void setMediaContentid(int mediaContentId) {
        this.mediaContentId = mediaContentId;
    }

    @Column(name = "CONTENTNAME", length = 320)
    public String getContentname() {
        return this.contentName;
    }

    public void setContentname(String contentName) {
        this.contentName = contentName;
    }

    @Column(name = "CODE", length = 160)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "CODE2", length = 160)
    public String getCode2() {
        return this.code2;
    }

    public void setCode2(String code2) {
        this.code2 = code2;
    }

    @Column(name = "TYPE", length = 1)
    public Character getType() {
        return this.type;
    }

    public void setType(Character type) {
        this.type = type;
    }

    @Column(name = "CLOSEDCAPTION", length = 1)
    public Character getClosedcaption() {
        return this.closedCaption;
    }

    public void setClosedcaption(Character closedCaption) {
        this.closedCaption = closedCaption;
    }

    @Column(name = "STATUS", length = 1)
    public Character getStatus() {
        return this.status;
    }

    public void setStatus(Character status) {
        this.status = status;
    }

    @Column(name = "SCREEN_FORMAT", length = 1)
    public Character getScreenFormat() {
        return this.screenFormat;
    }

    public void setScreenFormat(Character screenFormat) {
        this.screenFormat = screenFormat;
    }

    @Column(name = "AUDIOTYPE", precision = 1, scale = 0)
    public Boolean getAudiotype() {
        return this.audioType;
    }

    public void setAudiotype(Boolean audioType) {
        this.audioType = audioType;
    }

    @Column(name = "FILEURL", length = 2048)
    public String getFileurl() {
        return this.fileUrl;
    }

    public void setFileurl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    @Column(name = "CONTENTDEFID", precision = 9, scale = 0)
    public Integer getContentdefid() {
        return this.contentDefid;
    }

    public void setContentdefid(Integer contentDefid) {
        this.contentDefid = contentDefid;
    }

    @Column(name = "VSPID", precision = 9, scale = 0)
    public Integer getVspid() {
        return this.vspId;
    }

    public void setVspid(Integer vspId) {
        this.vspId = vspId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDATE", length = 7)
    public Date getCreatedate() {
        return this.createDate;
    }

    public void setCreatedate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "CREATESTAFFID", precision = 9, scale = 0)
    public Integer getCreatestaffid() {
        return this.createStaffid;
    }

    public void setCreatestaffid(Integer createStaffid) {
        this.createStaffid = createStaffid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATETIME", length = 7)
    public Date getLastupdatetime() {
        return this.lastUpdateTime;
    }

    public void setLastupdatetime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Column(name = "CDNDOMAINCODE", length = 16)
    public String getCdndomaincode() {
        return this.cdnDomainCode;
    }

    public void setCdndomaincode(String cdnDomainCode) {
        this.cdnDomainCode = cdnDomainCode;
    }

    @Column(name = "ORIGINALFILEURL", length = 2048)
    public String getOriginalfileUrl() {
        return this.originalFileUrl;
    }

    public void setOriginalfileUrl(String originalFileUrl) {
        this.originalFileUrl = originalFileUrl;
    }

    @Column(name = "INTERNALFLAG", length = 1)
    public Character getInternalflag() {
        return this.internalFlag;
    }

    public void setInternalflag(Character internalFlag) {
        this.internalFlag = internalFlag;
    }

    @Column(name = "PRIORITY", length = 1)
    public Character getPriority() {
        return this.priority;
    }

    public void setPriority(Character priority) {
        this.priority = priority;
    }

    @Column(name = "TRANSCODEFLAG", length = 1)
    public Character getTranscodeflag() {
        return this.transcodeFlag;
    }

    public void setTranscodeflag(Character transcodeFlag) {
        this.transcodeFlag = transcodeFlag;
    }

    @Column(name = "TCSORIGINALCONTENTDEFID", precision = 9, scale = 0)
    public Integer getTcsoriginalcontentDefid() {
        return this.tcsOriginalContentDefid;
    }

    public void setTcsoriginalcontentDefid(Integer tcsOriginalContentDefid) {
        this.tcsOriginalContentDefid = tcsOriginalContentDefid;
    }

    @Column(name = "TCSTARGETCONTENTDEFID", precision = 9, scale = 0)
    public Integer getTcstargetcontentDefid() {
        return this.tcsTargetContentDefid;
    }

    public void setTcstargetcontentDefid(Integer tcsTargetContentDefid) {
        this.tcsTargetContentDefid = tcsTargetContentDefid;
    }

    @Column(name = "TCSORIGINALFILEURL", length = 2048)
    public String getTcsoriginalFileUrl() {
        return this.tcsOriginalFileUrl;
    }

    public void setTcsoriginalFileUrl(String tcsOriginalFileUrl) {
        this.tcsOriginalFileUrl = tcsOriginalFileUrl;
    }

    @Column(name = "TCSSTATUS", length = 1)
    public Character getTcsstatus() {
        return this.tcsStatus;
    }

    public void setTcsstatus(Character tcsStatus) {
        this.tcsStatus = tcsStatus;
    }

    @Column(name = "AUDITFLAG", length = 1)
    public Character getAuditflag() {
        return this.auditFlag;
    }

    public void setAuditflag(Character auditFlag) {
        this.auditFlag = auditFlag;
    }

    @Column(name = "AUDITERRORCODE", length = 32)
    public String getAuditerrorcode() {
        return this.auditErrorCode;
    }

    public void setAuditerrorcode(String auditErrorCode) {
        this.auditErrorCode = auditErrorCode;
    }

    @Column(name = "AUDITERRORINFO", length = 1024)
    public String getAuditerrorinfo() {
        return this.auditErrorInfo;
    }

    public void setAuditerrorinfo(String auditErrorInfo) {
        this.auditErrorInfo = auditErrorInfo;
    }

    @Column(name = "AUDITRESULT", length = 4000)
    public String getAuditresult() {
        return this.auditResult;
    }

    public void setAuditresult(String auditResult) {
        this.auditResult = auditResult;
    }

    @Column(name = "CDNDISTRIBUTELEVEL", length = 16)
    public String getCdndistributelevel() {
        return this.cdnDistributeLevel;
    }

    public void setCdndistributelevel(String cdnDistributeLevel) {
        this.cdnDistributeLevel = cdnDistributeLevel;
    }

    @Column(name = "PARSERERRORCODE", length = 32)
    public String getParsererrorcode() {
        return this.parserErrorCode;
    }

    public void setParsererrorcode(String parserErrorCode) {
        this.parserErrorCode = parserErrorCode;
    }

    @Column(name = "PARSERERRORINFO", length = 1024)
    public String getParsererrorinfo() {
        return this.parserErrorInfo;
    }

    public void setParsererrorinfo(String parserErrorInfo) {
        this.parserErrorInfo = parserErrorInfo;
    }

    @Column(name = "DURATION", length = 20)
    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    @Column(name = "FILESIZE", precision = 20, scale = 0)
    public BigDecimal getFilesize() {
        return this.fileSize;
    }

    public void setFilesize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    @Column(name = "VERIFYCODE", length = 32)
    public String getVerifycode() {
        return this.verifyCode;
    }

    public void setVerifycode(String verifyCode) {
        this.verifyCode = verifyCode;
    }

    @Column(name = "TEMPFILENAME", length = 2048)
    public String getTempfilename() {
        return this.tempFileName;
    }

    public void setTempfilename(String tempFileName) {
        this.tempFileName = tempFileName;
    }

    @Column(name = "NASSERVERID", precision = 9, scale = 0)
    public Integer getNasserverid() {
        return this.nasServerId;
    }

    public void setNasserverid(Integer nasServerId) {
        this.nasServerId = nasServerId;
    }

}
