package cn.utstarcom.vmsadapter.md5verify.pojo;
// Generated 2017-11-20 17:00:17 by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "PROGRAM", schema = "WACOS")
public class Program implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private int programId;
    private String name;
    private String code;
    private Character status;
    private Character stockOutFlag;
    private Integer vspId;
    private String code2;
    private String alias;
    private String epiTitle;
    private String sName;
    private Character seriesFlag;
    private Integer epiSodeNum;
    private Integer epiSodeIndex;
    private String titleSortName;
    private String titleSearchName;
    private Date licensingWindowStart;
    private Date licensingWindowEnd;
    private BigDecimal price;
    private String kpeople;
    private String director;
    private String scriptWriter;
    private String compere;
    private String guest;
    private String reporter;
    private String opinCharge;
    private String orgairDate;
    private String duration;
    private String language;
    private String captionLanguage;
    private String copyright;
    private String crBegin;
    private String rtime;
    private String fcl;
    private String columnName;
    private String description;
    private String memo;
    private String paraChannel;
    private String recastTime1;
    private String recastChannel1;
    private String recastTime2;
    private String recastChannel2;
    private String recastTime3;
    private String recastChannel3;
    private String source;
    private String sourceMedia;
    private String pgmCategory;
    private String pgmsndclass;
    private String contentProvider;
    private String reserve1;
    private String reserve2;
    private String reserve3;
    private String reserve4;
    private String reserve5;
    private Date createDate;
    private Integer createStaffid;
    private Date lastUpdateTime;
    private Character sourceType;
    private Short labelType;
    private String genre;
    private String releaseYear;
    private String linkUrl;
    private String columnPath;
    private Date copyrightExpirationTime;
    private String videoBitrateName;
    private Character type1;
    private Character lockFlag;
    private String originalCountry;
    private Integer contentProviderId;
    private Integer copyrighterId;
    private Character editMode;
    private String labelIds;
    private Character autoFlag;
    private Integer md5ChkCnt;
    private Date md5ChkLastTime;
    private String rating;
    private String newPrice;
    private String tags;
    private Integer programType;
    private String viewPoint;
    private String starLevel;
    private String awards;

    public Program() {
    }

    public Program(int programId) {
        this.programId = programId;
    }

    public Program(int programId, String name, String code, Character status,
            Character stockOutFlag, Integer vspId, String code2, String alias, String epiTitle,
            String sName, Character seriesFlag, Integer epiSodeNum, Integer epiSodeIndex,
            String titleSortName, String titleSearchName, Date licensingWindowStart,
            Date licensingWindowEnd, BigDecimal price, String kpeople, String director,
            String scriptWriter, String compere, String guest, String reporter, String opinCharge,
            String orgairDate, String duration, String language, String captionLanguage,
            String copyright, String crBegin, String rtime, String fcl, String columnName,
            String description, String memo, String paraChannel, String recastTime1,
            String recastChannel1, String recastTime2, String recastChannel2, String recastTime3,
            String recastChannel3, String source, String sourceMedia, String pgmCategory,
            String pgmsndclass, String contentProvider, String reserve1, String reserve2,
            String reserve3, String reserve4, String reserve5, Date createDate,
            Integer createStaffid, Date lastUpdateTime, Character sourceType, Short labelType,
            String genre, String releaseYear, String linkUrl, String columnPath,
            Date copyrightExpirationTime, String videoBitrateName, Character type1,
            Character lockFlag, String originalCountry, Integer contentProviderId,
            Integer copyrighterId, Character editMode, String labelIds, Character autoFlag,
            Integer md5ChkCnt, Date md5ChkLastTime, String rating, String newPrice,
            String tags, Integer programType, String viewPoint, String starLevel, String awards) {
        this.programId = programId;
        this.name = name;
        this.code = code;
        this.status = status;
        this.stockOutFlag = stockOutFlag;
        this.vspId = vspId;
        this.code2 = code2;
        this.alias = alias;
        this.epiTitle = epiTitle;
        this.sName = sName;
        this.seriesFlag = seriesFlag;
        this.epiSodeNum = epiSodeNum;
        this.epiSodeIndex = epiSodeIndex;
        this.titleSortName = titleSortName;
        this.titleSearchName = titleSearchName;
        this.licensingWindowStart = licensingWindowStart;
        this.licensingWindowEnd = licensingWindowEnd;
        this.price = price;
        this.kpeople = kpeople;
        this.director = director;
        this.scriptWriter = scriptWriter;
        this.compere = compere;
        this.guest = guest;
        this.reporter = reporter;
        this.opinCharge = opinCharge;
        this.orgairDate = orgairDate;
        this.duration = duration;
        this.language = language;
        this.captionLanguage = captionLanguage;
        this.copyright = copyright;
        this.crBegin = crBegin;
        this.rtime = rtime;
        this.fcl = fcl;
        this.columnName = columnName;
        this.description = description;
        this.memo = memo;
        this.paraChannel = paraChannel;
        this.recastTime1 = recastTime1;
        this.recastChannel1 = recastChannel1;
        this.recastTime2 = recastTime2;
        this.recastChannel2 = recastChannel2;
        this.recastTime3 = recastTime3;
        this.recastChannel3 = recastChannel3;
        this.source = source;
        this.sourceMedia = sourceMedia;
        this.pgmCategory = pgmCategory;
        this.pgmsndclass = pgmsndclass;
        this.contentProvider = contentProvider;
        this.reserve1 = reserve1;
        this.reserve2 = reserve2;
        this.reserve3 = reserve3;
        this.reserve4 = reserve4;
        this.reserve5 = reserve5;
        this.createDate = createDate;
        this.createStaffid = createStaffid;
        this.lastUpdateTime = lastUpdateTime;
        this.sourceType = sourceType;
        this.labelType = labelType;
        this.genre = genre;
        this.releaseYear = releaseYear;
        this.linkUrl = linkUrl;
        this.columnPath = columnPath;
        this.copyrightExpirationTime = copyrightExpirationTime;
        this.videoBitrateName = videoBitrateName;
        this.type1 = type1;
        this.lockFlag = lockFlag;
        this.originalCountry = originalCountry;
        this.contentProviderId = contentProviderId;
        this.copyrighterId = copyrighterId;
        this.editMode = editMode;
        this.labelIds = labelIds;
        this.autoFlag = autoFlag;
        this.md5ChkCnt = md5ChkCnt;
        this.md5ChkLastTime = md5ChkLastTime;
        this.rating = rating;
        this.newPrice = newPrice;
        this.tags = tags;
        this.programType = programType;
        this.viewPoint = viewPoint;
        this.starLevel = starLevel;
        this.awards = awards;
    }

    @Id

    @Column(name = "PROGRAMID", unique = true, nullable = false, precision = 9, scale = 0)
    public int getProgramid() {
        return this.programId;
    }

    public void setProgramid(int programId) {
        this.programId = programId;
    }

    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "CODE", length = 160)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "STATUS", length = 1)
    public Character getStatus() {
        return this.status;
    }

    public void setStatus(Character status) {
        this.status = status;
    }

    @Column(name = "STOCKOUTFLAG", length = 1)
    public Character getStockoutflag() {
        return this.stockOutFlag;
    }

    public void setStockoutflag(Character stockOutFlag) {
        this.stockOutFlag = stockOutFlag;
    }

    @Column(name = "VSPID", precision = 9, scale = 0)
    public Integer getVspid() {
        return this.vspId;
    }

    public void setVspid(Integer vspId) {
        this.vspId = vspId;
    }

    @Column(name = "CODE2", length = 160)
    public String getCode2() {
        return this.code2;
    }

    public void setCode2(String code2) {
        this.code2 = code2;
    }

    @Column(name = "ALIAS", length = 510)
    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    @Column(name = "EPITITLE", length = 200)
    public String getEpititle() {
        return this.epiTitle;
    }

    public void setEpititle(String epiTitle) {
        this.epiTitle = epiTitle;
    }

    @Column(name = "SNAME", length = 300)
    public String getSname() {
        return this.sName;
    }

    public void setSname(String sName) {
        this.sName = sName;
    }

    @Column(name = "SERIESFLAG", length = 1)
    public Character getSeriesflag() {
        return this.seriesFlag;
    }

    public void setSeriesflag(Character seriesFlag) {
        this.seriesFlag = seriesFlag;
    }

    @Column(name = "EPISODENUM", precision = 9, scale = 0)
    public Integer getEpisodenum() {
        return this.epiSodeNum;
    }

    public void setEpisodenum(Integer epiSodeNum) {
        this.epiSodeNum = epiSodeNum;
    }

    @Column(name = "EPISODEINDEX", precision = 9, scale = 0)
    public Integer getEpisodeindex() {
        return this.epiSodeIndex;
    }

    public void setEpisodeindex(Integer epiSodeIndex) {
        this.epiSodeIndex = epiSodeIndex;
    }

    @Column(name = "TITLE_SORT_NAME", length = 320)
    public String getTitleSortName() {
        return this.titleSortName;
    }

    public void setTitleSortName(String titleSortName) {
        this.titleSortName = titleSortName;
    }

    @Column(name = "TITLE_SEARCH_NAME", length = 300)
    public String getTitleSearchName() {
        return this.titleSearchName;
    }

    public void setTitleSearchName(String titleSearchName) {
        this.titleSearchName = titleSearchName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LICENSINGWINDOWSTART", length = 7)
    public Date getLicensingwindowstart() {
        return this.licensingWindowStart;
    }

    public void setLicensingwindowstart(Date  licensingWindowStart) {
        this.licensingWindowStart = licensingWindowStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LICENSINGWINDOWEND", length = 7)
    public Date getLicensingwindowend() {
        return this.licensingWindowEnd;
    }

    public void setLicensingwindowend(Date  licensingWindowEnd) {
        this.licensingWindowEnd = licensingWindowEnd;
    }

    @Column(name = "PRICE", precision = 12)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "KPEOPLE", length = 300)
    public String getKpeople() {
        return this.kpeople;
    }

    public void setKpeople(String kpeople) {
        this.kpeople = kpeople;
    }

    @Column(name = "DIRECTOR", length = 100)
    public String getDirector() {
        return this.director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    @Column(name = "SCRIPTWRITER", length = 100)
    public String getScriptwriter() {
        return this.scriptWriter;
    }

    public void setScriptwriter(String scriptWriter) {
        this.scriptWriter = scriptWriter;
    }

    @Column(name = "COMPERE", length = 100)
    public String getCompere() {
        return this.compere;
    }

    public void setCompere(String compere) {
        this.compere = compere;
    }

    @Column(name = "GUEST", length = 100)
    public String getGuest() {
        return this.guest;
    }

    public void setGuest(String guest) {
        this.guest = guest;
    }

    @Column(name = "REPORTER", length = 100)
    public String getReporter() {
        return this.reporter;
    }

    public void setReporter(String reporter) {
        this.reporter = reporter;
    }

    @Column(name = "OPINCHARGE", length = 100)
    public String getOpincharge() {
        return this.opinCharge;
    }

    public void setOpincharge(String opinCharge) {
        this.opinCharge = opinCharge;
    }

    @Column(name = "ORGAIRDATE", length = 20)
    public String getOrgairdate() {
        return this.orgairDate;
    }

    public void setOrgairdate(String orgairDate) {
        this.orgairDate = orgairDate;
    }

    @Column(name = "DURATION", length = 20)
    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    @Column(name = "LANGUAGE", length = 150)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "CAPTIONLANGUAGE", length = 150)
    public String getCaptionlanguage() {
        return this.captionLanguage;
    }

    public void setCaptionlanguage(String captionLanguage) {
        this.captionLanguage = captionLanguage;
    }

    @Column(name = "COPYRIGHT", length = 100)
    public String getCopyright() {
        return this.copyright;
    }

    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    @Column(name = "CRBEGIN", length = 20)
    public String getCrbegin() {
        return this.crBegin;
    }

    public void setCrbegin(String crBegin) {
        this.crBegin = crBegin;
    }

    @Column(name = "RTIME", length = 20)
    public String getRtime() {
        return this.rtime;
    }

    public void setRtime(String rtime) {
        this.rtime = rtime;
    }

    @Column(name = "FCL", length = 300)
    public String getFcl() {
        return this.fcl;
    }

    public void setFcl(String fcl) {
        this.fcl = fcl;
    }

    @Column(name = "COLUMNNAME", length = 100)
    public String getColumnname() {
        return this.columnName;
    }

    public void setColumnname(String columnName) {
        this.columnName = columnName;
    }

    @Column(name = "DESCRIPTION", length = 4000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "MEMO", length = 4000)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "PARACHANNEL", length = 100)
    public String getParachannel() {
        return this.paraChannel;
    }

    public void setParachannel(String paraChannel) {
        this.paraChannel = paraChannel;
    }

    @Column(name = "RECASTTIME1", length = 20)
    public String getRecasttime1() {
        return this.recastTime1;
    }

    public void setRecasttime1(String recastTime1) {
        this.recastTime1 = recastTime1;
    }

    @Column(name = "RECASTCHANNEL1", length = 100)
    public String getRecastchannel1() {
        return this.recastChannel1;
    }

    public void setRecastchannel1(String recastChannel1) {
        this.recastChannel1 = recastChannel1;
    }

    @Column(name = "RECASTTIME2", length = 20)
    public String getRecasttime2() {
        return this.recastTime2;
    }

    public void setRecasttime2(String recastTime2) {
        this.recastTime2 = recastTime2;
    }

    @Column(name = "RECASTCHANNEL2", length = 100)
    public String getRecastchannel2() {
        return this.recastChannel2;
    }

    public void setRecastchannel2(String recastChannel2) {
        this.recastChannel2 = recastChannel2;
    }

    @Column(name = "RECASTTIME3", length = 20)
    public String getRecasttime3() {
        return this.recastTime3;
    }

    public void setRecasttime3(String recastTime3) {
        this.recastTime3 = recastTime3;
    }

    @Column(name = "RECASTCHANNEL3", length = 100)
    public String getRecastchannel3() {
        return this.recastChannel3;
    }

    public void setRecastchannel3(String recastChannel3) {
        this.recastChannel3 = recastChannel3;
    }

    @Column(name = "SOURCE", length = 100)
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Column(name = "SOURCEMEDIA", length = 100)
    public String getSourcemedia() {
        return this.sourceMedia;
    }

    public void setSourcemedia(String sourceMedia) {
        this.sourceMedia = sourceMedia;
    }

    @Column(name = "PGMCATEGORY", length = 100)
    public String getPgmcategory() {
        return this.pgmCategory;
    }

    public void setPgmcategory(String pgmCategory) {
        this.pgmCategory = pgmCategory;
    }

    @Column(name = "PGMSNDCLASS", length = 100)
    public String getPgmsndclass() {
        return this.pgmsndclass;
    }

    public void setPgmsndclass(String pgmsndclass) {
        this.pgmsndclass = pgmsndclass;
    }

    @Column(name = "CONTENTPROVIDER", length = 100)
    public String getContentprovider() {
        return this.contentProvider;
    }

    public void setContentprovider(String contentProvider) {
        this.contentProvider = contentProvider;
    }

    @Column(name = "RESERVE1", length = 150)
    public String getReserve1() {
        return this.reserve1;
    }

    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    @Column(name = "RESERVE2", length = 150)
    public String getReserve2() {
        return this.reserve2;
    }

    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    @Column(name = "RESERVE3", length = 150)
    public String getReserve3() {
        return this.reserve3;
    }

    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3;
    }

    @Column(name = "RESERVE4", length = 150)
    public String getReserve4() {
        return this.reserve4;
    }

    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4;
    }

    @Column(name = "RESERVE5", length = 150)
    public String getReserve5() {
        return this.reserve5;
    }

    public void setReserve5(String reserve5) {
        this.reserve5 = reserve5;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDATE", length = 7)
    public Date getCreatedate() {
        return this.createDate;
    }

    public void setCreatedate(Date  createDate) {
        this.createDate = createDate;
    }

    @Column(name = "CREATESTAFFID", precision = 9, scale = 0)
    public Integer getCreatestaffid() {
        return this.createStaffid;
    }

    public void setCreatestaffid(Integer createStaffid) {
        this.createStaffid = createStaffid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATETIME", length = 7)
    public Date getLastupdatetime() {
        return this.lastUpdateTime;
    }

    public void setLastupdatetime(Date  lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Column(name = "SOURCETYPE", length = 1)
    public Character getSourcetype() {
        return this.sourceType;
    }

    public void setSourcetype(Character sourceType) {
        this.sourceType = sourceType;
    }

    @Column(name = "LABELTYPE", precision = 4, scale = 0)
    public Short getLabeltype() {
        return this.labelType;
    }

    public void setLabeltype(Short labelType) {
        this.labelType = labelType;
    }

    @Column(name = "GENRE", length = 128)
    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    @Column(name = "RELEASEYEAR", length = 4)
    public String getReleaseyear() {
        return this.releaseYear;
    }

    public void setReleaseyear(String releaseYear) {
        this.releaseYear = releaseYear;
    }

    @Column(name = "LINKURL", length = 1024)
    public String getLinkurl() {
        return this.linkUrl;
    }

    public void setLinkurl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Column(name = "COLUMNPATH", length = 1024)
    public String getColumnpath() {
        return this.columnPath;
    }

    public void setColumnpath(String columnPath) {
        this.columnPath = columnPath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COPYRIGHTEXPIRATIONTIME", length = 7)
    public Date getCopyrightexpirationtime() {
        return this.copyrightExpirationTime;
    }

    public void setCopyrightexpirationtime(Date  copyrightExpirationTime) {
        this.copyrightExpirationTime = copyrightExpirationTime;
    }

    @Column(name = "VIDEOBITRATENAME", length = 320)
    public String getVideobitratename() {
        return this.videoBitrateName;
    }

    public void setVideobitratename(String videoBitrateName) {
        this.videoBitrateName = videoBitrateName;
    }

    @Column(name = "TYPE1", length = 1)
    public Character getType1() {
        return this.type1;
    }

    public void setType1(Character type1) {
        this.type1 = type1;
    }

    @Column(name = "LOCKFLAG", length = 1)
    public Character getLockflag() {
        return this.lockFlag;
    }

    public void setLockflag(Character lockFlag) {
        this.lockFlag = lockFlag;
    }

    @Column(name = "ORIGINALCOUNTRY", length = 64)
    public String getOriginalcountry() {
        return this.originalCountry;
    }

    public void setOriginalcountry(String originalCountry) {
        this.originalCountry = originalCountry;
    }

    @Column(name = "CONTENTPROVIDERID", precision = 9, scale = 0)
    public Integer getContentproviderid() {
        return this.contentProviderId;
    }

    public void setContentproviderid(Integer contentProviderId) {
        this.contentProviderId = contentProviderId;
    }

    @Column(name = "COPYRIGHTERID", precision = 9, scale = 0)
    public Integer getCopyrighterid() {
        return this.copyrighterId;
    }

    public void setCopyrighterid(Integer copyrighterId) {
        this.copyrighterId = copyrighterId;
    }

    @Column(name = "EDITMODE", length = 1)
    public Character getEditmode() {
        return this.editMode;
    }

    public void setEditmode(Character editMode) {
        this.editMode = editMode;
    }

    @Column(name = "LABELIDS", length = 1024)
    public String getLabelids() {
        return this.labelIds;
    }

    public void setLabelids(String labelIds) {
        this.labelIds = labelIds;
    }

    @Column(name = "AUTOFLAG", length = 1)
    public Character getAutoflag() {
        return this.autoFlag;
    }

    public void setAutoflag(Character autoFlag) {
        this.autoFlag = autoFlag;
    }

    @Column(name = "MD5CHKCNT", precision = 9, scale = 0)
    public Integer getMd5chkcnt() {
        return this.md5ChkCnt;
    }

    public void setMd5chkcnt(Integer md5ChkCnt) {
        this.md5ChkCnt = md5ChkCnt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MD5CHKLASTTIME", length = 7)
    public Date getMd5chklasttime() {
        return this.md5ChkLastTime;
    }

    public void setMd5chklasttime(Date  md5ChkLastTime) {
        this.md5ChkLastTime = md5ChkLastTime;
    }

    @Column(name = "RATING", length = 64)
    public String getRating() {
        return this.rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    @Column(name = "NEWPRICE", length = 100)
    public String getNewprice() {
        return this.newPrice;
    }

    public void setNewprice(String newPrice) {
        this.newPrice = newPrice;
    }

    @Column(name = "TAGS", length = 100)
    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    @Column(name = "PROGRAMTYPE", precision = 9, scale = 0)
    public Integer getProgramtype() {
        return this.programType;
    }

    public void setProgramtype(Integer programType) {
        this.programType = programType;
    }

    @Column(name = "VIEWPOINT", length = 256)
    public String getViewpoint() {
        return this.viewPoint;
    }

    public void setViewpoint(String viewPoint) {
        this.viewPoint = viewPoint;
    }

    @Column(name = "STARLEVEL", length = 2)
    public String getStarlevel() {
        return this.starLevel;
    }

    public void setStarlevel(String starLevel) {
        this.starLevel = starLevel;
    }

    @Column(name = "AWARDS", length = 128)
    public String getAwards() {
        return this.awards;
    }

    public void setAwards(String awards) {
        this.awards = awards;
    }

}
