package cn.utstarcom.vmsadapter.md5verify.pojo;
// Generated 2017-11-20 17:00:17 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProgramMediaContent generated by hbm2java
 */
@Entity
@Table(name = "PROGRAMMEDIACONTENT", schema = "WACOS", uniqueConstraints = @UniqueConstraint(columnNames = {
        "OBJTYPE", "OBJID", "MEDIACONTENTID" }))
public class ProgramMediaContent implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    private int programMediaContentId;
    private Character objType;
    private Integer objId;
    private Integer mediaContentId;

    public ProgramMediaContent() {
    }

    public ProgramMediaContent(int programMediaContentId) {
        this.programMediaContentId = programMediaContentId;
    }

    public ProgramMediaContent(int programMediaContentId, Character objType, Integer objId,
            Integer mediaContentId) {
        this.programMediaContentId = programMediaContentId;
        this.objType = objType;
        this.objId = objId;
        this.mediaContentId = mediaContentId;
    }

    @Id

    @Column(name = "PROGRAMMEDIACONTENTID", unique = true, nullable = false, precision = 9, scale = 0)
    public int getProgrammediaContentId() {
        return this.programMediaContentId;
    }

    public void setProgrammediaContentId(int programMediaContentId) {
        this.programMediaContentId = programMediaContentId;
    }

    @Column(name = "OBJTYPE", length = 1)
    public Character getObjtype() {
        return this.objType;
    }

    public void setObjtype(Character objType) {
        this.objType = objType;
    }

    @Column(name = "OBJID", precision = 9, scale = 0)
    public Integer getObjid() {
        return this.objId;
    }

    public void setObjid(Integer objId) {
        this.objId = objId;
    }

    @Column(name = "MEDIACONTENTID", precision = 9, scale = 0)
    public Integer getMediaContentid() {
        return this.mediaContentId;
    }

    public void setMediaContentid(Integer mediaContentId) {
        this.mediaContentId = mediaContentId;
    }

}
